### ISSUE TITLE
Add Better Poster template 

### ISSUE THREAD

**Issue by katyhuff** [arfc/poster-template#2]
The current poster template is great for standard poster presentations. 
However, there's another super cool way to make posters called "Better Poster". 

It would be great if this repository held templates for both, either as parallel top-level folders in the main branch of this repo, or as separate branches in the repo. I think the separate folders option is probably best. 

This issue can be closed with a PR that:
- moves the existing template into a top-level folder called something like "standard-poster"
- creates a new folder called "better-poster" which holds a latex template for the Better Poster style of poster.

Perhaps one can leverage an existing Better Poster LaTeX template like this one (please obey attribution rules if copying that template to this repo.) : https://github.com/rafaelbailo/betterposter-latex-template

**Comment by nsryan2** [comment]
Closed by #3
